# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-11 18:53
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Car',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(auto_now_add=True, verbose_name='运行日期')),
                ('name', models.CharField(choices=[('2287', '豫 A2287'), ('5658', '豫 A5658'), ('9809', '豫 A9809')], default='2287', max_length=20, unique_for_date='date', verbose_name='车名')),
                ('slug', models.SlugField(blank=True, max_length=200, verbose_name='标签')),
                ('total_income', models.FloatField(verbose_name='总收入')),
                ('real_income', models.FloatField(verbose_name='净收入')),
                ('total_people', models.IntegerField(verbose_name='总人数')),
                ('oil', models.FloatField(default=0, verbose_name='油钱')),
                ('people_30', models.IntegerField(default=0, verbose_name='30元票价人数')),
                ('people_40', models.IntegerField(default=0, verbose_name='40元票价人数')),
                ('things', models.IntegerField(default=0, verbose_name='货钱')),
                ('food', models.IntegerField(default=0, verbose_name='饭钱及其他额外花销')),
            ],
            options={
                'verbose_name_plural': '车辆列表',
                'db_table': 'car',
                'ordering': ('-date',),
            },
        ),
        migrations.CreateModel(
            name='Driver',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='姓名')),
            ],
            options={
                'verbose_name_plural': '司机列表',
                'db_table': 'car_driver',
            },
        ),
        migrations.CreateModel(
            name='DriverSalary',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('salary', models.FloatField(default=6000.0, verbose_name='工资')),
                ('borrow', models.FloatField(blank=True, default=0, null=True, verbose_name='借钱')),
                ('real_salary', models.FloatField(default=6000.0, verbose_name='实际工资')),
                ('date', models.DateField(auto_now_add=True, verbose_name='日期')),
                ('time', models.DateField(verbose_name='请假开始日期')),
                ('days', models.IntegerField(verbose_name='请假天数')),
                ('reason', models.TextField(blank=True, null=True, verbose_name='请假原因')),
                ('name', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='driversalary', to='car.Driver', verbose_name='姓名')),
            ],
            options={
                'verbose_name_plural': '司机工资列表',
                'db_table': 'car_driver_salary',
                'ordering': ('salary',),
            },
        ),
        migrations.CreateModel(
            name='Saler',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='姓名')),
            ],
            options={
                'verbose_name_plural': '售票员列表',
                'db_table': 'car_saler',
            },
        ),
        migrations.CreateModel(
            name='SalerSalary',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('salary', models.FloatField(default=2500.0, verbose_name='工资')),
                ('borrow', models.FloatField(blank=True, default=0, null=True, verbose_name='借钱')),
                ('real_salary', models.FloatField(default=2500.0, verbose_name='实际工资')),
                ('date', models.DateField(auto_now_add=True, verbose_name='日期')),
                ('time', models.DateField(verbose_name='请假开始日期')),
                ('days', models.IntegerField(verbose_name='请假天数')),
                ('reason', models.TextField(blank=True, null=True, verbose_name='请假原因')),
                ('name', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='salersalary', to='car.Saler', verbose_name='姓名')),
            ],
            options={
                'verbose_name_plural': '售票员工资列表',
                'db_table': 'car_saler_salary',
                'ordering': ('salary',),
            },
        ),
        migrations.AddField(
            model_name='car',
            name='driver',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cars', related_query_name='car', to='car.Driver', verbose_name='司机'),
        ),
        migrations.AddField(
            model_name='car',
            name='saler',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cars', related_query_name='car', to='car.Saler', verbose_name='售票员'),
        ),
    ]
